-- Criação da tabela de usuários
CREATE TABLE IF NOT EXISTS users (
    USR_ID       SERIAL PRIMARY KEY,
    USR_EMAIL    VARCHAR(255) NOT NULL UNIQUE,
    USR_NAME     VARCHAR(255) NOT NULL,
    USR_PASSWORD VARCHAR(255) NOT NULL,
    USR_IA_API_KEY VARCHAR(255)
);
 